#Drawing Shapes
print("     /|")
print("    / |")
print("   /  |")
print("  /   |")
print(" /    |")
print("/_____|")



#Variables $ Datatypes
character_name = "Kelvin"
character_age = "38"
character_school = "University Of Portharcourt"

print("there was a man named " + character_name + '')
print("he is " + character_age + " years old")
print("he really liked the named " + character_name + '')
print("but doesn't like being " + character_age + '')
print("he is also a student of " + character_school + '')

#Dictionaries

Month_conversions = [
    'mon', "Monday",
    'tue', "Tuesday",
    'wed', "Wednesday",
    'thur', "Thursday",
    'fri', "Friday",
    'sat', "Saturday",
    'sun', "Sunday",
]

print(Month_conversions.get(wed))
print(Month_conversions('fri'))






















